services:
  playwright:
    container_name: main-playwright-container
    image: my-playwright-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    command: mvn clean test