version: '3'
services:
  playwright:
    image: my-playwright-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    command: mvn clean test