services:
  playwright:
    container_name: main-playwright-container
    image: my-playwright-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - "C:/Users/issac/.m2:/root/.m2" # Maven cache
      - "C:/Users/issac/.cache/ms-playwright:/root/.cache/ms-playwright"  # Playwright browser cache
    working_dir: /workspace
    tty: true
    command: mvn clean test