package com.base;
import com.microsoft.playwright.Page;
import com.factory.PlayWrightFactory;
import com.procurement.currencyexchangerate.CurrencyExchangeRate;
import com.procurement.dispatchnotes.assign.DispatchNotesAssign;
import com.interfaces.DispatchNotesAssignInterface;
import com.procurement.dispatchnotes.create.DispatchNoteCreate;
import com.interfaces.DispatchNoteCreateInterface;
import com.procurement.inspections.assign.InspectionAssign;
import com.interfaces.InspectionAssignInterface;
import com.procurement.inspections.create.InspectionCreate;
import com.interfaces.InspectionCreateInterface;
import com.procurement.invoice.approve.POInvoiceApproval;
import com.interfaces.POInvoiceApprovalInterface;
import com.procurement.invoice.create.POInvoiceCreate;
import com.interfaces.POInvoiceCreateInterface;
import com.procurement.invoice.sendforapproval.POInvoiceSendForApproval;
import com.interfaces.POSendForApprovalInterface;
import com.procurement.login.LoginPage;
import com.interfaces.LoginPageInterface;
import com.interfaces.LogoutPageInterface;
import com.procurement.logout.LogoutPage;
import com.procurement.msa.PorInspectPO;
import com.interfaces.PorInspectPoInterface;
import com.procurement.orderschedule.approve.OrderScheduleApprove;
import com.interfaces.OrderScheduleApproveInterface;
import com.procurement.orderschedule.create.OrderScheduleCreate;
import com.interfaces.OrderScheduleInterface;
import com.procurement.purchaseorder.BuyerPurchaseOrder;
import com.interfaces.PurchaseOrderInterface;
import com.procurement.purchaseorderrequest.approval.PocPorApproval;
import com.interfaces.PorApproval;
import com.procurement.purchaseorderrequest.create.PocNonCatalogPorCreate;
import com.interfaces.PorCreateNonCatalog;
import com.procurement.requestforquotations.commercialevaluation.CommercialEvaluation;
import com.interfaces.CommercialEvaluationInterface;
import com.procurement.requestforquotations.create.PocRfqCreate;
import com.interfaces.RfqCreate;
import com.procurement.requestforquotations.edit.PocRfqEdit;
import com.interfaces.RfqEdit;
import com.interfaces.QuotationSubmit;
import com.procurement.requestforquotations.quotationsubmit.RegisteredVendorQuotationSubmit;
import com.procurement.requestforquotations.readyforevaluation.ReadyForEvaluation;
import com.interfaces.ReadyForEvalutationInterface;
import com.procurement.requestforquotations.suspend.PocRfqSuspend;
import com.interfaces.RfqSuspend;
import com.procurement.requestforquotations.technicalevaluation.TechnicalEvaluation;
import com.interfaces.TechnicalEvaluationInterface;
import com.procurement.requisition.approve.PocPrApprove;
import com.interfaces.PrApprove;
import com.procurement.requisition.edit.PocPrEdit;
import com.interfaces.PrEdit;
import com.procurement.requisition.reject.PocPrReject;
import com.interfaces.PrReject;
import com.procurement.requisition.assign.PocPrAssign;
import com.interfaces.PrAssign;
import com.procurement.requisition.create.PocNonCatalogPrCreate;
import com.interfaces.PrCreateNonCatalog;
import com.procurement.requisition.sendforapproval.PocPrSendForApproval;
import com.interfaces.PrSendForApproval;
import com.procurement.requisition.suspend.PocPrBuyerManagerSuspend;
import com.procurement.requisition.suspend.PocPrBuyerSuspend;
import com.interfaces.PrSuspend;
import com.procurement.workorder.create.WorkOrderCreate;
import com.interfaces.WorkOrderCreateInterface;
import com.procurement.workorder.trackerstatus.WOTrackerStatus;
import com.interfaces.WOTrackerStatusInterface;
import java.util.Properties;

public class BaseMain {
    protected PlayWrightFactory playWrightFactory;
    protected Page page;
    protected Properties properties;
    protected CurrencyExchangeRate currencyExchangeRate;
    protected LoginPageInterface loginPageInterface;
    protected LogoutPageInterface logoutPageInterface;
    protected PrCreateNonCatalog prCreateNonCatalog;
    protected PrEdit prEdit;
    protected PrSendForApproval prSendForApproval;
    protected PrApprove prApprove;
    protected PrReject prReject;
    protected PrSuspend prSuspendBuyerManager;
    protected PrSuspend prSuspendBuyer;
    protected PrAssign prAssign;
    protected RfqCreate rfqCreate;
    protected RfqEdit rfqEdit;
    protected RfqSuspend rfqSuspend;
    protected QuotationSubmit quotationSubmit;
    protected ReadyForEvalutationInterface readyForEvalutationInterface;
    protected TechnicalEvaluationInterface technicalEvaluationInterface;
    protected CommercialEvaluationInterface commercialEvaluationInterface;
    protected PorCreateNonCatalog porCreateNonCatalog;
    protected PorApproval porApproval;
    protected PorInspectPoInterface porInspectPoInterface;
    protected PurchaseOrderInterface purchaseOrderInterface;
    protected OrderScheduleInterface orderScheduleInterface;
    protected OrderScheduleApproveInterface orderScheduleApproveInterface;
    protected InspectionCreateInterface inspectionCreateInterface;
    protected InspectionAssignInterface inspectionAssignInterface;
    protected DispatchNoteCreateInterface dispatchNoteCreateInterface;
    protected DispatchNotesAssignInterface dispatchNotesAssignInterface;
    protected WorkOrderCreateInterface workOrderCreateInterface;
    protected WOTrackerStatusInterface woTrackerStatusInterface;
    protected POInvoiceCreateInterface poInvoiceCreateInterface;
    protected POSendForApprovalInterface poSendForApprovalInterface;
    protected POInvoiceApprovalInterface poInvoiceApprovalInterface;

//TODO Constructor
    public BaseMain() {
            playWrightFactory = new PlayWrightFactory();
            properties = playWrightFactory.initializeProperties();
            page = playWrightFactory.initializeBrowser(properties);

            loginPageInterface = new LoginPage(properties, page);
            logoutPageInterface = new LogoutPage(page);

//TODO Requisition
            prCreateNonCatalog = new PocNonCatalogPrCreate(loginPageInterface, properties, page, logoutPageInterface);
            prApprove = new PocPrApprove(loginPageInterface, properties, page, logoutPageInterface);
            prSendForApproval = new PocPrSendForApproval(loginPageInterface, properties, page, logoutPageInterface);
            prAssign = new PocPrAssign(loginPageInterface, properties, page, logoutPageInterface);
            prEdit = new PocPrEdit(loginPageInterface, properties, page, logoutPageInterface, prSendForApproval, prApprove, prAssign);
            prReject = new PocPrReject(loginPageInterface, properties, page, logoutPageInterface, prEdit);
            prSuspendBuyerManager = new PocPrBuyerManagerSuspend(loginPageInterface, properties, page, logoutPageInterface, prEdit);
            prSuspendBuyer = new PocPrBuyerSuspend(loginPageInterface, properties, page, logoutPageInterface, prEdit);

//TODO Request For Quotation
            rfqCreate = new PocRfqCreate(loginPageInterface, properties, page, logoutPageInterface);
            rfqEdit = new PocRfqEdit(loginPageInterface, properties, page, logoutPageInterface);
            rfqSuspend = new PocRfqSuspend(loginPageInterface, properties, page, logoutPageInterface, rfqEdit, prEdit, prSendForApproval, prApprove, prAssign, rfqCreate);
            quotationSubmit = new RegisteredVendorQuotationSubmit(loginPageInterface, properties, page, logoutPageInterface);
            readyForEvalutationInterface = new ReadyForEvaluation(loginPageInterface, properties, page, logoutPageInterface);
            technicalEvaluationInterface = new TechnicalEvaluation(loginPageInterface, properties, page, logoutPageInterface);
            commercialEvaluationInterface = new CommercialEvaluation(loginPageInterface, properties, page, logoutPageInterface);

//TODO Purchase Order Request
            porCreateNonCatalog = new PocNonCatalogPorCreate(loginPageInterface, properties, page, logoutPageInterface);
            porApproval = new PocPorApproval(loginPageInterface, properties, page, logoutPageInterface);
            porInspectPoInterface = new PorInspectPO(loginPageInterface, properties, page, logoutPageInterface);
            purchaseOrderInterface = new BuyerPurchaseOrder(loginPageInterface, properties, page, logoutPageInterface);
            orderScheduleInterface = new OrderScheduleCreate(loginPageInterface, properties, page, logoutPageInterface, playWrightFactory);
            orderScheduleApproveInterface = new OrderScheduleApprove(loginPageInterface, properties, page, logoutPageInterface);
            inspectionCreateInterface = new InspectionCreate(loginPageInterface, properties, page, logoutPageInterface);
            inspectionAssignInterface = new InspectionAssign(loginPageInterface, properties, page, logoutPageInterface);
            dispatchNoteCreateInterface = new DispatchNoteCreate(loginPageInterface, properties, page, logoutPageInterface);
            dispatchNotesAssignInterface = new DispatchNotesAssign(loginPageInterface, properties, page, logoutPageInterface);
            workOrderCreateInterface = new WorkOrderCreate(loginPageInterface, properties, page, logoutPageInterface);
            woTrackerStatusInterface = new WOTrackerStatus(loginPageInterface, properties, page, logoutPageInterface);
            poInvoiceCreateInterface = new POInvoiceCreate(playWrightFactory, loginPageInterface, properties, page, logoutPageInterface, currencyExchangeRate);
            poSendForApprovalInterface = new POInvoiceSendForApproval(loginPageInterface, properties, page, logoutPageInterface);
            poInvoiceApprovalInterface = new POInvoiceApproval(loginPageInterface, properties, page, logoutPageInterface);
            currencyExchangeRate = new CurrencyExchangeRate(playWrightFactory, loginPageInterface, properties, logoutPageInterface);
    }
}