name: GePS-HOPES-YEA Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress
        working-directory: GePS-Testing/GePS-HOPES-YEA

      - name: Ensure browsers are installed
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"
        working-directory: GePS-Testing/GePS-HOPES-YEA

      - name: Run tests
        run: mvn clean test -DSELENIUM_REMOTE_URL=http://localhost:4444 -DsuiteXmlFile=src/test/resources/testrunners/GePS-HOPES_YEA_functional-test.xml
        working-directory: GePS-Testing/GePS-HOPES-YEA
