name: GePS-HOPES_YEA Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    description: 'GePS-HOPES_YEA Test Workflow'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install GUI dependencies (Ubuntu 24.04 compatible)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libatk1.0-0 libatk-bridge2.0-0 \
            libcups2 libxss1 libasound2t64 libgbm-dev

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress
        working-directory: ./GePS-HOPES_YEA

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"
        working-directory: ./GePS-HOPES_YEA

      - name: Run Tests (supports headless & headed)
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' \
            mvn clean test -DsuiteXmlFile=src/test/resources/testrunners/GePS-HOPES_YEA_functional-test.xml
        working-directory: ./GePS-HOPES_YEA
